Hw04 lru cache
astak/otus-golang-homework pull request #4
Opened 2024-05-11 05:49 UTC by astak

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-05-11 06:12 UTC, vladislavmass requested changes

2024-05-11 06:12 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if i.Next != nil {
Не совсем понимаю зачем нужна эта проверка, если по сути это блок else к предыдущем, так как единственная ситуация когда `next==nil`, это когда мы работаем с элементом равным back

2024-05-11 06:12 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if i.Prev != nil {
При какой ситуации не сработает данный код? Насколько я вижу единственную ситуация пропуска этого кода мы обработали в строках с 86 по 88

2024-05-11 06:12 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.front != nil {
Данный if тоже выглядит так, как будто при нормальных условиях он будет срабатывать всегда

2024-05-11 06:12 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	if cache.queue.Len() > cache.capacity {
Размер очереди не должен превышать капасити пусть даже и на очень не значительный промежуток

2024-05-12 18:16 UTC, astak commented on hw04_lru_cache/list.go
> +	if i.Next != nil {
Со всеми тремя замечаниями по этому методу согласен, но в процессе осмысления и переписывания все варианты показались мне недостаточно ясными. В попытках сделать код легко читаемым, пришел к следующему решению: вынес логику удаления и добавления в отдельные методы, а метод MoveToFront реализовал через них.

2024-05-12 18:17 UTC, astak commented on hw04_lru_cache/list.go
> +	if i.Prev != nil {
см. предыдущий комментарий

2024-05-12 18:17 UTC, astak commented on hw04_lru_cache/list.go
> +	if l.front != nil {
см. предыдущий комментарий

2024-05-12 18:17 UTC, astak commented on hw04_lru_cache/cache.go
> +	if cache.queue.Len() > cache.capacity {
✔️

2024-05-13 04:15 UTC, vladislavmass approved these changes

2024-05-13 05:08 UTC, merged